version: '2.4'
services:
 jenkins:
    depends_on:
      artifactory:
        condition: service_healthy
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "8880:8080"
    volumes:
      - ./jenkins_controller/casc.yml:/usr/share/jenkins/ref/casc.yml
    restart: always